import { z } from 'zod';

const num = z.number();
const int = z.number().int();
/** 奖励（邀请等配置里用）：和后台补偿同样的五项 */
const idNum = z.object({ id: int, num: int.min(1) });
const rewardSchema = z.object({
  coin: int.min(1).optional(),
  diamond: int.min(1).optional(),
  exp: int.min(1).optional(),
  goods: z.array(idNum).optional(),
  foods: z.array(idNum).optional(),
});
/** 一番赏的奖品（和活动奖励同样的六项） */
const kujiAward = z.object({
  coin: int.min(1).optional(),
  exp: int.min(1).optional(),
  diamond: int.min(1).optional(),
  renown: int.min(1).optional(),
  goods: z.array(idNum).optional(),
  foods: z.array(idNum).optional(),
});
const kujiNews = z.enum(['broadcast', 'news']).optional();
const levelWeights = z.array(z.tuple([int, num])).min(1);
/** 一番赏一条线的档位和最后赏（普通池、豪华池共用） */
const kujiTiers = z
  .array(
    z.object({
      key: z.string().min(1).max(4),
      count: int.min(1),
      award: kujiAward,
      icon: z.string().min(1).optional(),
      news: kujiNews,
    }),
  )
  .min(1);
const kujiLast = z.object({ award: kujiAward, icon: z.string().min(1).optional(), news: kujiNews });

/** 数值常量（data/game/tuning.json）。区服可以通过 shard_config.override.tuning 覆盖任意字段 */
export const tuningSchema = z.object({
  rest: z.object({
    atRateBase: num,
    atRatePerStar: num,
    spRateBase: num,
    spRatePerStar: num,
    localRateBase: num,
    localRatePerStar: num,
    oilBase: num,
    coinBase: num,
    expBase: num,
    handleRateBase: num,
    handleRatePerStar: num,
    tablesPerFloor: int.min(1),
    attrPerLevel: int,
    luckPerLevel: int,
    tablesPerLevel: int,
    cookbookMaxGrade: int.min(1).max(10),
  }),
  settlement: z.object({
    atFloatBase: num,
    atFloatPerStar: num,
    spFloatPerStar: num,
    spFloatCenter: num,
    atOverflowThreshold: num,
    atOverflowDivisor: num,
    adiaoOverflowRate: num,
    negativeRenownAtRate: num,
    starPotential: z.array(num),
    cteRate: num,
    planktonRateBase: num,
    planktonRatePerStar: num,
    planktonMultiplier: num,
    /** 赶走痞老板的店多少小时内不再被选为驻留店（原版没有；小区服里总是同一家） */
    planktonHostCooldownHours: num,
    /** 全服经营经验倍率：每桌经验和挑剔消耗食材经验都乘它（原作为 1） */
    expMultiplier: z.number().positive(),
    /** 全服银币倍率：每桌付费顾客的银币乘它（148-4 全服加成用，默认 1） */
    coinMultiplier: z.number().positive(),
    /** 菜价倍率（问题记录 240-1）：挑剔顾客、蟹老板按菜价付钱和外卖单价都乘它 */
    dishCoinRate: z.number().positive(),
    roachRateBase: num,
    roachRatePerStar: num,
    /** 一家店同时最多多少比例的桌子是蟑螂桌（向上取整，至少 1 张）；自然长的和好友放的合计（问题记录 228） */
    roachMaxShare: z.number().min(0).max(1),
    squidwardRate: num,
    squidwardMinStar: int,
    squidwardOtherStreetFactor: num,
    squidwardPortions: int,
    krabRate: num,
    krabSameStreetFactor: num,
    krabLuckDivisor: num,
    krabMaxGrade: int,
    krabExpPerGrade: num,
    krabCoinMultiplier: num,
    huskyRate: num,
    painting13Rate: num,
    painting13Hours: num,
    pickyMaxGrade: int,
    cookfoodsPerFlag: int,
    cookfoodsMaxFlag: int,
    cookfoodsMinGrade: int,
    cookfoodsNeedGradeCap: int,
    dtTicketBaseRate: num,
    dtTicketLuckDivisor: num,
    dtTicketOddsDivisor: num,
    krabCoinBaseRate: num,
    krabCoinOddThreshold: num,
    krabCoinOddStep: num,
    renownRate: num,
    renownOddThreshold: num,
    autoRefuelThreshold: int,
    concurrency: int.min(1),
    batchSize: int.min(1),
  }),
  collection: z.object({
    plaquePer: num,
    an2023Multiplier: num,
    honorPer: num,
    mdcgMultiplier: num,
    an2025CoinBonus: num,
  }),
  strength: z.object({ regen: int, luckyRegen: int }),
  mouse: z.object({
    rateBase: num,
    ratePerStar: num,
    newbieFactor: num,
    luckDivisor: num,
    trapCoinPerLevel: num,
  }),
  growth: z.object({
    plaque2Star: int,
    plaque2Coin: int,
    plaque2Diamond: int,
    cookfoodsMinStar: int,
    driveKrabStrength: int,
    drivePlanktonStrength: int,
    drivePlanktonRenownPerSqrt: int,
    drivePlanktonExpPerRenown: int,
    drivePlanktonBookExpPerRenown: int,
    renameCoinPerRoach: int,
    renameMaxLength: int,
    /** 升到第 N 星付的银币，第 N 个数；没写的星不收（问题记录 240-1） */
    starCoin: z.array(int.min(0)),
    /** 搬街费 ×（1 + 星级 × 这个值）（问题记录 240-1） */
    moveStarRate: num.min(0),
  }),
  cupboard: z.object({
    handleMax: int.min(1),
    freeHandleBase: int,
    freeHandlePerStar: int,
    thawCoinRate: num,
    failCoinRate: num,
    exchangeMaxTimes: int.min(1),
  }),
  market: z.object({
    dailyHours: z.array(int).min(1),
    dailyKinds: int,
    dailyKindsLastHour: int,
    dailyKindsLast: int,
    dailyStock: int,
    dailyRareStock: int,
    dailyLevelWeights: levelWeights,
    specialHours: z.array(int).min(1),
    specialKinds: int,
    specialHotChance: num,
    specialStockBase: int,
    specialStockRand: int,
    specialPrice: int,
    specialLevelWeights: levelWeights,
    premiumHours: z.array(int).min(1),
    premiumKinds: int,
    premiumStock: int,
    premiumRareFactor: num,
    premiumLevel: int,
    premiumPriceFactor: num,
    /** 菜场价格倍率：三个货架的单价在天气系数之后再乘它（148-4 全服加成用，默认 1） */
    priceFactor: z.number().positive(),
    /** 各等级食材的价格倍数，第 N 个是 N 级；没写的等级按 1（问题记录 240-1） */
    levelPriceRate: z.array(z.number().positive()),
    shelfLimits: z.tuple([int, int, int]),
    rareWindowMinutes: int,
    rareLimitOddsFactor: num,
    rareLimitBase: int,
    specialIpCooldownSec: int,
    hotMinNeedCount: int,
    guessCost: int,
    guessMaxPick: int.min(1),
    guessBonusHours: z.array(int),
    manualCost: int.min(0),
    manualKinds: int.min(1),
    manualStock: int.min(1),
    manualPersonMax: int.min(1),
    manualShare: num.min(0).max(1),
  }),
  shop: z.object({
    sellRate: num,
    specialHour: int,
    specialFallbackGoods: int,
    discardable: z.array(int),
    maxBuy: int.min(1),
  }),
  store: z.object({ maxBatch: int.min(1) }),
  world: z.object({
    weatherHours: z.array(int).min(1),
    nightFrom: int,
    nightTo: int,
    krabHour: int,
    krabStreetMin: int,
    krabStreetMax: int,
    nightWeatherOdds: z.array(z.tuple([int, num])),
    dayWeightScale: num,
  }),
  friend: z.object({
    requireVerifiedEmail: z.boolean(),
    maxFriends: int.min(1),
    dine: z.object({
      minMinutes: int.min(0),
      strengthPerHour: int,
      strengthMax: int,
      heartExpMul: num,
      heartStrengthMul: num,
      baseSeats: int.min(0),
    }),
    roach: z.object({
      layBase: int,
      layLevelRate: num,
      layCoin: int,
      layExp: int,
      killCoin: int,
      killExp: int,
      killCoinLevelRate: num,
      killSelfRate: num,
      killStrength: z.object({ self: int, friend: int, npc: int }),
      ticketRate: num,
      ticketMax: int.min(1),
    }),
    flip: z.object({
      baseSlots: int.min(1),
      slotsPerStar: int,
      coolHours: num,
      coolRandHours: num,
      npcCoolHours: num,
      cheapTimes: int,
      caughtCoinPerLevel: int,
      npcCaughtCoinPerStar: int,
      hitRate: num,
      blessedRate: num,
      handleFoodsRate: num,
      handleFoodsRatePerStar: num,
      luckDivisor: z.number().positive(),
    }),
    exchange: z.object({
      maxLevel: int,
      base: int,
      feeRate: num,
      lockedFeeMul: num,
      perDayTotalMul: int,
      takenBase: int,
      npcBase: int,
      stormCaughtRate: num,
      bangleBase: num,
      bangleFactor: num,
    }),
    thumbs: z.object({ rewardTimes: int, ticketMax: int, overRenown: int, strengthMax: int.min(1) }),
    refuel: z.object({ bigTank: int.min(2), drawsPerChunk: int }),
    npc: z.object({
      name: z.string().min(1),
      level: int.min(1),
      star: int.min(0),
      tables: int.min(1),
      oil: int.min(1),
      avatar: int,
      door: int,
      roachRate: num,
      restockKinds: int.min(1),
      restockNum: int.min(1),
    }),
  }),
  equip: z.object({
    maxStress: int.min(1),
    baseRate: num,
    ratePerStress: num,
    /** 连续失败每次加的成功率（保底） */
    floorPerFail: num,
    coinPerEssence: int,
    /** 强化到这一级起发新闻 */
    newsFromStress: int,
    gemBaseRate: num,
    gemRatePerLevel: num,
    gemExpPerLevel: int,
    /** 升阶成功得到的宝石阶数大于它时发新闻 */
    gemNewsLevel: int,
    /** 下一阶不小于它且有失败时发新闻 */
    gemBrokenNewsLevel: int,
    ungemCoinPerLevel: int,
    /** 从这个星级起摘除宝石要花银币 */
    ungemMinStar: int,
    maxPresets: int.min(1),
    historyLimit: int.min(1),
  }),
  mysterious: z.object({
    cookNums: z.array(int.min(1)).min(1),
    baseNum: int,
    /** 等级大于它的特色菜份数打折 */
    highLevel: int,
    highLevelNumRange: z.tuple([num, num]),
    /** 品级 2~7 的下限（规格书 04 §4.5 mcGradeRate） */
    gradeBounds: z.array(num).length(6),
    /** 品级 1~7 的份数系数区间（mcGradeRatio） */
    gradeRatio: z.array(z.tuple([num, num])).length(7),
    levelBonusPerLevel: num,
    roadSame: num,
    roadSameMax: num,
    roadOther: num,
    roadOtherMax: num,
    cookNumPowerDiv: num,
    bobRatePerNutritive: num,
    appraiseRetryBelow: int,
    tasteDaily: int.min(1),
    tasteAwardMax: int,
    tasteMcRate: num,
    tasteGradeFactor: num,
    lessonLearnRate: num,
    lessonStealRate: num,
    lessonStealPerLevel: num,
    thinkerStealBonus: num,
    learnStrength: int,
    stealStrength: int,
    tuitionTimes: num,
    teacherShare: num,
    learnFragments: int,
    teacherFragments: int,
    forgetPerLevel: int,
    forgetMcFromLevel: int,
    forgetMcPerLevel: num,
    forceCloseCoinPerLevel: int,
    championHour: int.min(0).max(23),
    championGoodsId: int,
  }),
  temple: z.object({
    guardianHpBase: int,
    guardianHpPerStar: int,
    missileTicketRate: num,
    missileMapRate: num,
    guardianRareRate: num,
    guardianFoodsBase: int,
    guardianFoodsSpread: int,
    injectCoin: int,
    refreshCoin: int,
    trialCoin: int,
    trialWorthMax: int,
    trialExpMax: int,
    trialProficiencyPerLevel: int,
    trialCap: num,
    rareOdds: int,
    krakenHours: z.array(z.tuple([int, int])).min(1),
    krakenRates: z.object({ same: num, road: num, other: num }),
    krabCoinRate: num,
    tentacleFavor: int,
    tentacleRate: num,
    forgetRate: num,
    shopSlots: int.min(1),
    shopExclude: z.array(int),
    /** 飞弹伤害覆盖：[道具 id, 最小, 最大]（试玩修复 14：极速飞弹太强） */
    missileAttack: z.array(z.tuple([int, int.min(0), int.min(0)])),
  }),
  yard: z.object({
    maxLands: int.min(1),
    landBaseCoin: int,
    landMaxLevel: int.min(1),
    yieldPerLevel: num,
    dryWaterSub: int,
    dryWaterMinRate: num,
    removeSeedRate: num,
    stealKeepRate: num,
    stealMax: int.min(1),
    reapPunishRate: num,
    seedShop: z.boolean(),
    seedPriceRate: num,
    formulaMainRate: num,
    formulaAppraiseRatePerLuck: num,
    composeStrength: int,
    composeCritRate: num,
    essenceMain: int,
    essenceSub: int,
    events: z.object({
      minutes: z.array(int.min(0).max(59)).min(1),
      nightMinute: int.min(0).max(59),
      dayFrom: int.min(0).max(23),
      dayTo: int.min(1).max(24),
      wormEatRate: num,
      grassEatRate: num,
      dryDeath: int,
      grassRate: num,
      grassDryFactor: num,
      dryAddRate: num,
      dryStartRate: num,
      dryStartGrassRate: num,
      wormRate: num,
    }),
  }),
  bar: z.object({
    fgWinRate: num,
    fgDrawRate: num,
    fgNewsStreak: int.min(1),
    cupNewsStreak: int.min(1),
    numMax: int.min(2),
    numCost: int.min(1),
    numLuckDiv: num,
    numAwardLevel: int.min(1),
    krabCoinTickets: int.min(1),
    slotCells: int.min(1),
    slotFloorSpins: int.min(1),
    slotFloorRate: num,
    slotFloorAwardId: int,
    awardRates: z.object({ foods: num, goods: num, coin: num, exp: num }),
    /** 魔鬼辣杯（子项目 4C-3） */
    devil: z.object({
      stakes: z.array(int.min(1)).min(1),
      cups: int.min(2),
      rate: num.min(1),
      hangoverMinutes: int.min(0),
      hangoverAtRate: num,
      newsSurvived: int.min(1),
    }),
    /** 记忆调酒 */
    memory: z.object({
      cost: int.min(0),
      dailyMax: int.min(1),
      ingredients: int.min(2),
      lengths: z.array(int.min(1)).min(1),
      awardLevels: z.array(int.min(1)).min(1),
      flashMs: int.min(1),
      gapMs: int.min(0),
      earlyMs: int.min(0),
      answerBaseMs: int.min(0),
      answerPerItemMs: int.min(0),
    }),
    /** 飞镖 */
    darts: z.object({
      cost: int.min(0),
      dailyMax: int.min(1),
      periodMs: z.tuple([int.min(100), int.min(100)]),
      futureMs: int.min(0),
      latencyMs: int.min(0),
      rings: z.array(z.tuple([num, int])).min(1),
      bossOdds: z.array(z.tuple([int, int.min(0)])).min(1),
      winLevel: int.min(1),
      perfectLevel: int.min(1),
      tieRefund: int.min(0),
    }),
  }),
  tower: z.object({
    dailyBase: int.min(0),
    nightFloor: int.min(0),
    openHour: int.min(0).max(23),
    testStrength: int.min(0),
    strengthPerFloor: int.min(0),
    strengthBase: int.min(0),
    winRenownBase: int,
    loseRenown: int,
    rankSize: int.min(1).max(15),
    rankTop: int.min(0),
    rankGap: int.min(1),
    rankDaily: int.min(1),
    rankWinRenown: int,
    rankLoseRenown: int,
    rankGifts: z.array(z.tuple([int, int])).min(1),
    duelStrength: int.min(0),
    duelPerFriend: int.min(1),
    duelWeakRate: num,
    duelStrongRate: num,
    duelRenown: z.object({
      weak: z.tuple([int, int]),
      strong: z.tuple([int, int]),
      normal: z.tuple([int, int]),
    }),
    sparFullAt: int.min(0),
    sparFullRenown: int,
    sparMaxAt: int.min(0),
    sparAwards: z.array(z.tuple([int, int.min(0), int.min(1)])).min(1),
    sparEquipFlag: int.min(0),
    watchmanCook: z.object({ hour: int.min(0).max(23), minute: int.min(0).max(59), priceSpread: num }),
  }),
  takeaway: z.object({
    openStar: int.min(0),
    openRenown: int.min(0),
    openCoin: int.min(0),
    openDiamond: int.min(0),
    publicBase: int.min(0),
    publicRand: int.min(1),
    publicPerOpen: int.min(1),
    publicMinOpen: int.min(0),
    publicOpenFloor: int.min(0),
    gradeRates: z.array(num).length(7),
    minutesBase: int.min(1),
    minutesPerGrade: int.min(1),
    renownPerGrade: int.min(0),
    refreshNum: int.min(1),
    refreshCoin: int.min(0),
    refreshRenown: int.min(0),
    priceLine: int.min(1),
    coinRates: z.tuple([num, num]),
    expRates: z.tuple([num, num]),
    expDiv: num,
    successFloat: int.min(2),
    luckOddsRate: num,
    privateExpRate: num,
    friendRiderRate: num,
    rebateDiv: int.min(1),
    failExpRate: num,
    customer: z.object({ base: num, luckDiv: num, success: int, fail: int }),
    rider: z.object({
      maxLevel: int.min(1),
      expPerLevel2: int.min(0),
      expBase: int.min(1),
      timeSubMax: int.min(0),
      expAdd: int.min(0),
      coinAdd: int.min(0),
      renownEvery: int.min(1),
      oddsBase: int.min(0),
      oddsPerLevel: int.min(0),
      oddsMax: int.min(0),
      maxNumEvery: int.min(1),
      capLevels: z.array(int),
      dismissCoin: int.min(0),
      dismissExp: int.min(0),
    }),
    awards: z.array(z.tuple([int, int.min(0), num])).min(1),
    keepOpenDays: int.min(0),
    keepDoneDays: int.min(0),
  }),
  town: z.object({
    broadcast: z.object({ minStar: int.min(0), cooldownSec: int.min(0), maxLen: int.min(1) }),
    npc: z.object({
      bigEaterLevelWeights: z.array(num.min(0)).length(5),
      bigEaterNum: z.tuple([int.min(1), int.min(1)]),
      wenjieNum: z.tuple([int.min(1), int.min(1)]),
      bro13Num: z.tuple([int.min(1), int.min(1)]),
    }),
    shake: z.object({
      base: int.min(1),
      rand: int.min(1),
      eggMod: int.min(1),
      eggTail: int.min(0),
      burgerEvery: int.min(1),
      burgerNum: int.min(1),
      krabCoinNum: int.min(1),
      limitIp: z.boolean(),
      limitDevice: z.boolean(),
      krabDailyCoin: int.min(0),
    }),
    hammer: z.object({
      cooldownHours: num.min(0),
      gapSec: int.min(0),
      coin: int.min(0),
      diamond: int.min(0),
    }),
    bless: z.object({ lampCoinBonus: num.min(0) }),
    news: z.object({ pageSize: int.min(1).max(200) }),
    rareExchange: z.boolean(),
    mysteryExclude: z.array(int),
    exchangeMaxNum: int.min(1),
  }),
  hiphop: z.object({
    hour: int.min(0).max(23),
    closeHour: int.min(1).max(24),
    weeklyHour: int.min(0).max(23),
    placeWeights: z.array(z.tuple([int, num.min(0)])).min(1),
    restActiveDays: int.min(1),
    worthBase: int.min(1),
    worthMin: num.min(0),
    worthRand: num.min(0),
    krabRate: num.min(0),
    foodFactor: num.min(0),
    coinMax: int.min(1),
    coinWorthDiv: num.min(1),
    coinExpDiv: num.min(1),
    diamondMax: int.min(1),
    diamondWorthNum: int.min(1),
    diamondWorthDen: int.min(1),
    diamondExpMul: num.min(0),
    expJitter: num.min(0).max(1),
    requireVerifiedEmail: z.boolean(),
    weeklyCards: z.array(int).min(1),
    wages: z.array(z.tuple([int, int])),
  }),
  rank: z.object({ top: int.min(1), cacheSeconds: int.min(0), powerCacheSeconds: int.min(0) }),
  mail: z.object({ expiresDays: int.min(1), listMax: int.min(1).max(500) }),
  invite: z.object({
    monthlyCap: int.min(1),
    levels: z.object({ lv10: int.min(1), lv30: int.min(1) }),
    newbie: rewardSchema,
    rewards: z.object({ lv10: rewardSchema, lv30: rewardSchema }),
  }),
  report: z.object({ dailyMax: int.min(1) }),
  ops: z.object({
    suspicious: z.object({
      barPerfectDaily: int.min(1),
      dartsBullDaily: int.min(1),
      sharedAccounts: int.min(2),
      topN: int.min(1).max(200),
    }),
  }),
  redeem: z.object({ failLimit: int.min(1), failWindowSec: int.min(1), batchMax: int.min(1).max(1000) }),
  /** 自由交易市场（156-1） */
  exchange: z.object({
    minLevel: int.min(1),
    minAccountDays: int.min(0),
    feeRate: z.number().min(0).max(0.5),
    bandLow: z.number().positive().max(1),
    bandHigh: z.number().min(1),
    refMinTrades: int.min(1),
    maxOpenOrders: int.min(1),
    orderHours: int.min(1),
    maxQty: int.min(1).max(999),
    /** 进阶防作弊（156-2） */
    suspicious: z.object({
      traceDays: int.min(1),
      edgeHigh: z.number().min(1),
      edgeLow: z.number().positive().max(1),
      repeatDays: int.min(1),
      repeatCount: int.min(2),
      largeAmount: int.min(1),
      holdHours: int.min(0),
    }),
    /** 系统做市（156-3） */
    maker: z
      .object({
        enabled: z.boolean(),
        bidRate: z.number().positive(),
        askRate: z.number().positive(),
        /** 不超过 1：否则从菜场买来卖给系统能赚钱（156-3 终审 I3） */
        marketCapRate: z.number().positive().max(1),
        dailyBuy: int.min(0),
        stockMax: int.min(0),
        playerDaily: int.min(0),
      })
      // 收购倍数要低于卖出倍数，否则从系统买进再卖回给系统能赚钱（156-3 终审 I3）
      .refine((m) => m.bidRate < m.askRate, { message: 'bidRate 要小于 askRate' }),
    // 不超过单价上限 1 亿：再大价格下限就超过单价上限，任何挂单都过不了校验（backlog 156-1）
    refOverrides: z.record(z.string(), int.min(1).max(100_000_000)),
  }),
  /** 事件合约（238-1） */
  predict: z.object({
    unit: int.min(1),
    feeRate: z.number().min(0).max(0.5),
    maxHold: int.min(1),
    maxTrade: int.min(1).max(999),
    defaultB: int.min(10).max(10000),
    minLevel: int.min(1),
    minAccountDays: int.min(0),
    /** 系统自动出题（238-2） */
    auto: z.object({
      krab: z.boolean(),
      market: z.boolean(),
      weather: z.boolean(),
      stats: z.boolean(),
      b: int.min(10).max(10000),
      marketCloseMin: int.min(1).max(60),
      statsCloseHour: int.min(1).max(23),
    }),
  }),
  /** 一番赏 */
  kuji: z.object({
    price: int.min(1),
    dailyBuy: int.min(1),
    maxDraw: int.min(1).max(100),
    activeTickets: int.min(0),
    /** 领活跃度这一档时送券（问题记录 318：新增 180 档后仍在 150 档送） */
    activeTicketPoints: int.min(1),
    /** 每个区服每天最多开几池（问题记录 274） */
    maxPools: int.min(1),
    tiers: kujiTiers,
    last: kujiLast,
    /** 豪华一番赏（240-2）：一条独立的奖池线，结构和普通池的价格、限购、档位、最后赏相同 */
    deluxe: z.object({
      price: int.min(1),
      dailyBuy: int.min(1),
      maxDraw: int.min(1).max(100),
      maxPools: int.min(1),
      tiers: kujiTiers,
      last: kujiLast,
    }),
  }),
  /** 个人缺料倾向（问题记录 50、68）：随机食材有 p 的概率改成本街学菜正缺的；p = min(上限, 基础 + 幸运率 × 系数) */
  scarcity: z
    .object({
      needBase: z.number().min(0).max(1),
      needLuckFactor: z.number().min(0),
      needMax: z.number().min(0).max(1),
    })
    .refine((s) => s.needBase <= s.needMax, { message: 'scarcity needBase must not exceed needMax' }),
  /** 小镇发展基金（240-2）：存期、到期领回和提前取出的比例、三档 */
  fund: z.object({
    days: int.min(1),
    returnRate: z.number().gt(0).max(1),
    earlyRate: z.number().gt(0).max(1),
    tiers: z
      .array(
        z.object({
          key: z.string().min(1).max(16),
          coin: int.min(1),
          medal: int.min(1),
          news: z.enum(['broadcast', 'news']).optional(),
        }),
      )
      .min(1),
  }),
  forum: z.object({
    titleMax: int.min(1),
    contentMax: int.min(1),
    replyMax: int.min(1),
    queryMax: int.min(1),
    postCooldownSec: int.min(0),
    postDailyMax: int.min(1),
    replyCooldownSec: int.min(0),
    pageSize: int.min(1).max(100),
    excerpt: int.min(1),
    readsMax: int.min(1),
    featureReward: z.object({ goods: z.array(z.tuple([int, int.min(1)])), diamond: int.min(0) }),
  }),
});

export type Tuning = z.infer<typeof tuningSchema>;
