import { z } from 'zod';

const num = z.number();
const int = z.number().int();
const levelWeights = z.array(z.tuple([int, num])).min(1);

/** 数值常量（data/game/tuning.json）。区服可以通过 shard_config.override.tuning 覆盖任意字段 */
export const tuningSchema = z.object({
  rest: z.object({
    atRateBase: num,
    atRatePerStar: num,
    spRateBase: num,
    spRatePerStar: num,
    localRateBase: num,
    localRatePerStar: num,
    oilBase: num,
    coinBase: num,
    expBase: num,
    handleRateBase: num,
    handleRatePerStar: num,
    tablesPerFloor: int.min(1),
    attrPerLevel: int,
    luckPerLevel: int,
    tablesPerLevel: int,
    cookbookMaxGrade: int.min(1).max(10),
  }),
  settlement: z.object({
    atFloatBase: num,
    atFloatPerStar: num,
    spFloatPerStar: num,
    spFloatCenter: num,
    atOverflowThreshold: num,
    atOverflowDivisor: num,
    adiaoOverflowRate: num,
    negativeRenownAtRate: num,
    starPotential: z.array(num),
    cteRate: num,
    planktonRateBase: num,
    planktonRatePerStar: num,
    planktonMultiplier: num,
    /** 全服经营经验倍率：每桌经验和挑剔消耗食材经验都乘它（原作为 1） */
    expMultiplier: num,
    roachRateBase: num,
    roachRatePerStar: num,
    squidwardRate: num,
    squidwardMinStar: int,
    squidwardOtherStreetFactor: num,
    squidwardPortions: int,
    krabRate: num,
    krabSameStreetFactor: num,
    krabLuckDivisor: num,
    krabMaxGrade: int,
    krabExpPerGrade: num,
    krabCoinMultiplier: num,
    huskyRate: num,
    painting13Rate: num,
    painting13Hours: num,
    pickyMaxGrade: int,
    cookfoodsPerFlag: int,
    cookfoodsMaxFlag: int,
    cookfoodsMinGrade: int,
    cookfoodsNeedGradeCap: int,
    dtTicketBaseRate: num,
    dtTicketLuckDivisor: num,
    dtTicketOddsDivisor: num,
    krabCoinBaseRate: num,
    krabCoinOddThreshold: num,
    krabCoinOddStep: num,
    renownRate: num,
    renownOddThreshold: num,
    autoRefuelThreshold: int,
    concurrency: int.min(1),
    batchSize: int.min(1),
  }),
  collection: z.object({
    plaquePer: num,
    an2023Multiplier: num,
    honorPer: num,
    mdcgMultiplier: num,
    an2025CoinBonus: num,
  }),
  strength: z.object({ regen: int, luckyRegen: int }),
  mouse: z.object({
    rateBase: num,
    ratePerStar: num,
    newbieFactor: num,
    luckDivisor: num,
    trapCoinPerLevel: num,
  }),
  growth: z.object({
    plaque2Star: int,
    plaque2Coin: int,
    plaque2Diamond: int,
    cookfoodsMinStar: int,
    driveKrabStrength: int,
    drivePlanktonStrength: int,
    drivePlanktonRenownPerSqrt: int,
    drivePlanktonExpPerRenown: int,
    drivePlanktonBookExpPerRenown: int,
    renameCoinPerRoach: int,
    renameMaxLength: int,
  }),
  cupboard: z.object({
    handleMax: int.min(1),
    freeHandleBase: int,
    freeHandlePerStar: int,
    thawCoinRate: num,
    failCoinRate: num,
    exchangeMaxTimes: int.min(1),
  }),
  market: z.object({
    dailyHours: z.array(int).min(1),
    dailyKinds: int,
    dailyKindsLastHour: int,
    dailyKindsLast: int,
    dailyStock: int,
    dailyRareStock: int,
    dailyLevelWeights: levelWeights,
    specialHours: z.array(int).min(1),
    specialKinds: int,
    specialHotChance: num,
    specialStockBase: int,
    specialStockRand: int,
    specialPrice: int,
    specialLevelWeights: levelWeights,
    premiumHours: z.array(int).min(1),
    premiumKinds: int,
    premiumStock: int,
    premiumRareFactor: num,
    premiumLevel: int,
    premiumPriceFactor: num,
    shelfLimits: z.tuple([int, int, int]),
    rareWindowMinutes: int,
    rareLimitOddsFactor: num,
    rareLimitBase: int,
    specialIpCooldownSec: int,
    hotMinNeedCount: int,
    guessCost: int,
    guessMaxPick: int.min(1),
    guessBonusHours: z.array(int),
  }),
  shop: z.object({
    sellRate: num,
    specialHour: int,
    specialFallbackGoods: int,
    discardable: z.array(int),
    maxBuy: int.min(1),
  }),
  store: z.object({ batchUsable: z.array(int), maxBatch: int.min(1) }),
  world: z.object({
    weatherHours: z.array(int).min(1),
    nightFrom: int,
    nightTo: int,
    krabHour: int,
    krabStreetMin: int,
    krabStreetMax: int,
    nightWeatherOdds: z.array(z.tuple([int, num])),
    dayWeightScale: num,
  }),
});

export type Tuning = z.infer<typeof tuningSchema>;
