import type { BarDto } from '@dt/shared';

export const barData = (patch: Partial<BarDto> = {}): BarDto => ({
  tickets: 20,
  coin: 0,
  krabCoins: 3,
  wenjieTalked: false,
  fg: { result: null, times: 0 },
  cup: {
    result: null,
    times: 0,
    cost: 1,
    cups: [2, 3, 5, 7],
    tiers: [
      { awards: 1, news: null },
      { awards: 2, news: null },
      { awards: 4, news: 'news' },
      { awards: 8, news: 'broadcast' },
    ],
    round: null,
  },
  num: { result: null, times: 0, cost: 8, max: 25 },
  slot: {
    emailVerified: true,
    lamp: false,
    floorLeft: 100,
    pool: [
      { id: 0, kind: 'empty', itemId: null, rate: 0.77, rare: false },
      { id: 1, kind: 'foods', itemId: 101, rate: 0.2, rare: false },
      { id: 100, kind: 'goods', itemId: 180, rate: 0.03, rare: true },
    ],
    stats: [],
  },
  krabCoinTickets: 100,
  devil: { stakes: [1, 5, 10, 20], round: null },
  memory: { cost: 1, played: 0, max: 20, flashMs: 600, gapMs: 200, round: null },
  darts: { cost: 2, played: 0, max: 20, round: null },
  nim: {
    played: 0,
    max: 10,
    tables: {
      novice: {
        cost: 1,
        k: [3, 3],
        pile: [10, 20],
        renown: 1,
        awardLevel: 2,
        first: 'choose',
        careless: true,
      },
      expert: {
        cost: 2,
        k: [3, 5],
        pile: [20, 40],
        renown: 3,
        awardLevel: 5,
        first: 'coin',
        careless: false,
      },
    },
    round: null,
  },
  deal: {
    cost: 10000,
    played: 0,
    max: 3,
    count: 10,
    opens: [3, 2, 2, 1],
    prizes: [
      { kind: 'food', level: 1, num: 1 },
      { kind: 'food', level: 1, num: 3 },
      { kind: 'food', level: 2, num: 2 },
      { kind: 'master', level: 1, num: 2 },
      { kind: 'food', level: 3, num: 2 },
      { kind: 'food', level: 4, num: 2 },
      { kind: 'food', level: 5, num: 2 },
      { kind: 'master', level: 3, num: 2 },
      { kind: 'master', level: 5, num: 2 },
      { kind: 'master', level: 5, num: 5 },
    ],
    round: null,
  },
  spice: {
    cost: 2,
    played: 0,
    max: 5,
    kinds: 10,
    length: 4,
    tries: 8,
    tiers: [
      { maxTries: 4, awardLevel: 8, renown: 5 },
      { maxTries: 6, awardLevel: 5, renown: 2 },
      { maxTries: 8, awardLevel: 3, renown: 0 },
    ],
    round: null,
  },
  ...patch,
});
