/**
 * 限时活动可选的行为（设计 §4.1）：只列服务端确实会发 action 事件的键。
 * 服务端有测试保证每个键都有 emitAction 调用
 */
export const ACTIVITY_ACTIONS: Readonly<Record<string, string>> = {
  signin: '签到',
  'oil.fill': '给自己添油',
  'attr.allocate': '分配属性点',
  'cookbook.learn': '学习或升级食谱',
  'market.buy': '菜场买菜',
  'market.guess': '菜场竞猜',
  'shop.buy': '商店购买道具',
  'device.place': '摆放设施',
  'foods.handle': '合成或分解食材',
  'foods.exchange': '和好友交换食材',
  'roach.kill': '打蟑螂',
  'roach.lay': '放置蟑螂',
  'friend.dineAndDash': '白食',
  'friend.refuel': '帮好友添油',
  'cupboard.flip': '翻厨',
  'thumbs.up': '给好友点赞',
  'krab.shake': '摇蟹老板的钱袋',
  'bar.play': '酒吧娱乐',
  'bar.slot': '老虎机',
  'bar.devil': '魔鬼辣杯',
  'bar.darts': '飞镖',
  'bar.memory': '记忆调酒',
  'tower.challenge': '厨塔挑战',
  'tower.friendDuel': '与好友切磋',
  'tower.rank': '赛厨榜挑战',
  'temple.explore': '神殿探险',
  'temple.missile': '挑战守护兽',
  'temple.trial': '神殿试炼',
  'kraken.feed': '投喂克拉肯',
  'mc.cook': '烹制特色菜',
  'mc.appraise': '鉴定特色菜',
  'lesson.learn': '上课学特色菜',
  'lesson.start': '开课',
  'formula.appraise': '鉴定配方',
  'formula.compose': '合成配方',
  'yard.plant': '菜园种地',
  'yard.harvest': '菜园收获',
  'yard.steal': '偷菜',
  'takeaway.deliver': '配送外卖',
  'equip.stress': '强化厨具',
  'equip.gemIn': '镶嵌宝石',
  'equip.drill': '厨具打孔',
  'hiphop.reward': '打赏嘻哈男孩',
  'post.create': '论坛发帖',
  broadcast: '发喇叭',
};
