import type {
  AccountProfileDto,
  AcquireMarketDto,
  AcquireRankDto,
  AcquireRestDto,
  AcquireResultDto,
  AcquireTendDto,
  AcquireViewDto,
  OpenCookbookBrief,
  OpenCookbookDto,
  OpenEquipsDto,
  OpenFoodBrief,
  OpenFoodDto,
  OpenGoodsBrief,
  OpenGoodsDto,
  OpenIndexDto,
  OpenListDto,
  OpenStreetDto,
  ChangePasswordInput,
  ForumAdminAction,
  ForumAdminDto,
  ForumListDto,
  ForumPostBody,
  ForumPostDetailDto,
  ForumPostSourceDto,
  ForumReactDto,
  ForumReadsDto,
  ForumReplyBody,
  ForumReplyDto,
  ForumTab,
  HiphopSpotDto,
  HiphopTipBody,
  HiphopTipDto,
  DartsAimDto,
  DartsDto,
  DartsThrowDto,
  DevilDto,
  MemoryAnswerDto,
  MemoryRoundDto,
  NimDto,
  SpiceDto,
  DealDto,
  FeastResultDto,
  HammerResultDto,
  NewsPageDto,
  DailyDto,
  NpcKey,
  ShakeResultDto,
  TalkResultDto,
  LeaderboardDto,
  ManualStockDto,
  TicketResultDto,
  TownDto,
  TownExchangeDto,
  TownExchangePart,
  TownExchangeResultDto,
  WishResultDto,
  BarDto,
  BarExchangeResultDto,
  CupDto,
  FgResultDto,
  NumResultDto,
  SlotResultDto,
  BasketDto,
  ComposeResultDto,
  FormulaAppraiseResultDto,
  FormulasDto,
  FriendYardDto,
  ReapResultDto,
  SeedsDto,
  YardDto,
  ExploreResultDto,
  KrakenFeedDto,
  MissileResultDto,
  TempleDto,
  TentacleShopDto,
  TrialResultDto,
  AppraiseResultDto,
  CookResultDto,
  LessonLearnDto,
  LessonsDto,
  McOverviewDto,
  McPreviewDto,
  TasteResultDto,
  ActivationDto,
  AttrResultDto,
  BuffsDto,
  CatalogDto,
  CookbookDetailDto,
  CookbookListDto,
  CookbookProgressDto,
  CupboardDto,
  DeviceOptionsDto,
  DineCurrentDto,
  DineRewardDto,
  EquipBatchDto,
  EquipDetailDto,
  EquipDto,
  EquipOverviewDto,
  ExchangeFoodsDto,
  ExchangeResultDto,
  FlipResultDto,
  FlipSlotsDto,
  FoodsNeedDto,
  ForgotPasswordInput,
  FridgeDto,
  GemLevelUpDto,
  GemsDto,
  FriendRequestDto,
  FriendRestDto,
  FriendsDto,
  HandleResultDto,
  IncomePageDto,
  KillResultDto,
  LearnResultDto,
  LedgerRecordDto,
  LogPageDto,
  LoginInput,
  MarketDto,
  MeDto,
  MyLooksDto,
  MoveCostDto,
  OilNeedDto,
  RegisterInput,
  ResetPasswordInput,
  RestBriefDto,
  RestaurantDto,
  ReturnAllDto,
  SelectShardResult,
  ShardDto,
  ShopDto,
  ShopSpecialDto,
  StarNeedDto,
  StoreDto,
  StressResultDto,
  TableDto,
  QuestsDto,
  ThawResultDto,
  ThumbResultDto,
  ThumbTodayDto,
  WorldDto,
  DuelInfoDto,
  DuelResultDto,
  RankDto,
  RenownShopDto,
  TowerDto,
  RiderCandidateDto,
  TakeawayClaimDto,
  TakeawayDeliveryDto,
  TakeawayDto,
  AnnouncementsDto,
  ActivitiesDto,
  ActivityClaimDto,
  ActivityExchangeDto,
  ExchangeBookDto,
  ExchangeFoodDto,
  ExchangeMeDto,
  ExchangeOrderDto,
  ExchangePlaceDto,
  ExchangeWithdrawDto,
  FuturesContractDto,
  FuturesDto,
  FuturesOrderInput,
  PredictDetailDto,
  KujiDrawDto,
  KujiLine,
  KujiViewDto,
  LinkDto,
  ServerTimeDto,
  FundViewDto,
  WealthViewDto,
  BulkBidInput,
  BulkDto,
  PredictListDto,
  PredictTradeDto,
  ActivitySummaryDto,
  MailClaimAllDto,
  MailClaimDto,
  MailListDto,
  GuideCodeDto,
  RedeemResultDto,
  ReportInput,
  InviteDto,
  Locale,
} from '@dt/shared';
import { SHARED_FOODS } from '@dt/shared';
import { api } from './client';

type Empty = Record<string, never>;
type Anything = Record<string, unknown>;
const qs = (q: Record<string, string | number | undefined>) => {
  const s = new URLSearchParams();
  for (const [k, v] of Object.entries(q)) if (v !== undefined) s.set(k, String(v));
  const str = s.toString();
  return str ? `?${str}` : '';
};

export const endpoints = {
  me: () => api.get<MeDto>('/api/v1/account/me'),
  register: (body: RegisterInput) => api.post<MeDto>('/api/v1/account/register', body),
  login: (body: LoginInput) => api.post<MeDto>('/api/v1/account/login', body),
  /** 账号语言（问题记录 272） */
  setLang: (lang: Locale) => api.post<{ lang: Locale }>('/api/v1/account/lang', { lang }),
  logout: () => api.post<Empty>('/api/v1/account/logout'),
  sendVerifyEmail: () => api.post<Empty>('/api/v1/account/send-verify-email'),
  verifyEmail: (token: string) => api.post<Empty>('/api/v1/account/verify-email', { token }),
  forgotPassword: (body: ForgotPasswordInput) => api.post<Empty>('/api/v1/account/forgot-password', body),
  resetPassword: (body: ResetPasswordInput) => api.post<Empty>('/api/v1/account/reset-password', body),
  accountProfile: () => api.get<AccountProfileDto>('/api/v1/account/profile'),
  /** relogin：密码已改但本机没换上新会话，要用新密码重新登录 */
  changePassword: (body: ChangePasswordInput) =>
    api.post<{ relogin?: boolean }>('/api/v1/account/change-password', body),
  listShards: () => api.get<ShardDto[]>('/api/v1/shard/list'),
  selectShard: (shardId: number) => api.post<SelectShardResult>('/api/v1/shard/select', { shardId }),
  createRestaurant: (name: string) => api.post<RestaurantDto>('/api/v1/restaurant/create', { name }),
  overview: () => api.get<RestaurantDto>('/api/v1/restaurant/overview'),
  floor: () => api.get<TableDto[]>('/api/v1/restaurant/floor'),
  income: (before?: string) => api.get<IncomePageDto>(`/api/v1/restaurant/income${qs({ before })}`),
  buffs: () => api.get<BuffsDto>('/api/v1/restaurant/buffs'),
  restLog: (before?: string) => api.get<LogPageDto>(`/api/v1/restaurant/log${qs({ before })}`),

  weather: () => api.get<WorldDto>('/api/v1/world/weather'),
  /** 道具目录：按语言返回名字（问题记录 272） */
  catalog: (lang: Locale) => api.get<CatalogDto>(`/api/v1/world/catalog?lang=${lang}`),
  /** 开放接口（问题记录 142）：Wiki 用，不用登录 */
  openIndex: (lang: Locale) => api.getPublic<OpenIndexDto>(`/api/v1/open?lang=${lang}`),
  openGoods: (lang: Locale) => api.getPublic<OpenListDto<OpenGoodsBrief>>(`/api/v1/open/goods?lang=${lang}`),
  openGoodsDetail: (lang: Locale, id: number) =>
    api.getPublic<OpenGoodsDto>(`/api/v1/open/goods/${id}?lang=${lang}`),
  openFoods: (lang: Locale) => api.getPublic<OpenListDto<OpenFoodBrief>>(`/api/v1/open/foods?lang=${lang}`),
  openFood: (lang: Locale, id: number) => api.getPublic<OpenFoodDto>(`/api/v1/open/foods/${id}?lang=${lang}`),
  openCookbooks: (lang: Locale) =>
    api.getPublic<OpenListDto<OpenCookbookBrief>>(`/api/v1/open/cookbooks?lang=${lang}`),
  openCookbook: (lang: Locale, id: number) =>
    api.getPublic<OpenCookbookDto>(`/api/v1/open/cookbooks/${id}?lang=${lang}`),
  openEquips: (lang: Locale) => api.getPublic<OpenEquipsDto>(`/api/v1/open/equips?lang=${lang}`),
  openStreets: (lang: Locale) =>
    api.getPublic<OpenListDto<OpenStreetDto>>(`/api/v1/open/streets?lang=${lang}`),

  starNeed: () => api.get<StarNeedDto>('/api/v1/growth/star'),
  oilNeed: () => api.get<OilNeedDto>('/api/v1/growth/oil'),
  devices: () => api.get<DeviceOptionsDto>('/api/v1/growth/devices'),
  allocate: (b: { cook: number; cutting: number; fire: number }) =>
    api.post<AttrResultDto>('/api/v1/growth/allocate', b),
  refuel: () => api.post<{ oil: number }>('/api/v1/growth/refuel'),
  starUp: () => api.post<{ star: number }>('/api/v1/growth/star-up'),
  oilExpand: () => api.post<Anything>('/api/v1/growth/oil-expand'),
  placeDevice: (slot: number, goodsId: number) =>
    api.post<Anything>('/api/v1/growth/device/place', { slot, goodsId }),
  removeDevice: (slot: number) => api.post<Anything>('/api/v1/growth/device/remove', { slot }),
  openPlaque2: () => api.post<Anything>('/api/v1/growth/plaque2'),
  rename: (name: string) => api.post<{ name: string }>('/api/v1/growth/rename', { name }),
  moveCost: () => api.get<MoveCostDto>('/api/v1/growth/move'),
  move: (streetId: number) => api.post<{ streetId: number }>('/api/v1/growth/move', { streetId }),
  setPromo: (on: boolean) => api.post<Anything>('/api/v1/growth/promo', { on }),
  setCookfoods: (flag: number) => api.post<Anything>('/api/v1/growth/cookfoods', { flag }),
  setCte: (on: boolean) => api.post<Anything>('/api/v1/growth/cte', { on }),
  drivePlankton: (way: 'strength' | 'book') => api.post<Anything>('/api/v1/growth/plankton/drive', { way }),
  driveKrab: () => api.post<Anything>('/api/v1/growth/krab/drive'),

  cookbookList: (q: { street: number; page: number; filter: string }) =>
    api.get<CookbookListDto>(`/api/v1/cookbook/list${qs(q)}`),
  cookbookProgress: () => api.get<CookbookProgressDto>('/api/v1/cookbook/progress'),
  cookbookDetail: (id: number) => api.get<CookbookDetailDto>(`/api/v1/cookbook/detail/${id}`),
  foodsNeed: (q: { street?: number; target: number; foodLevel?: number }) =>
    api.get<FoodsNeedDto>(`/api/v1/cookbook/foods-need${qs(q)}`),
  learn: (cookbookId: number) => api.post<LearnResultDto>('/api/v1/cookbook/learn', { cookbookId }),

  cupboard: () => api.get<CupboardDto>('/api/v1/cupboard/list'),
  fridge: () => api.get<FridgeDto>('/api/v1/cupboard/fridge'),
  readFridge: () => api.post<Anything>('/api/v1/cupboard/fridge/read'),
  lockFood: (foodsId: number) => api.post<Anything>('/api/v1/cupboard/lock', { foodsId }),
  unlockFood: (foodsId: number) => api.post<Anything>('/api/v1/cupboard/unlock', { foodsId }),
  thaw: (foodsId: number) => api.post<ThawResultDto>('/api/v1/cupboard/thaw', { foodsId }),
  handleFoods: (b: { foodsId: number; way: 'compose' | 'decompose'; num: number }) =>
    api.post<HandleResultDto>('/api/v1/cupboard/handle', b),
  exchangeMaster: (
    foodsId: typeof SHARED_FOODS.masterLevel1 | typeof SHARED_FOODS.masterLevel2,
    times: number,
  ) => api.post<Anything>('/api/v1/cupboard/exchange', { foodsId, times }),

  market: () => api.get<MarketDto>('/api/v1/market/view'),
  marketBuy: (itemId: number, num: number) => api.post<Anything>('/api/v1/market/buy', { itemId, num }),
  marketManualStock: () => api.post<ManualStockDto>('/api/v1/market/manual-stock'),
  marketGuess: (foodsIds: number[]) => api.post<{ period: string }>('/api/v1/market/guess', { foodsIds }),

  shop: () => api.get<ShopDto>('/api/v1/shop/items'),
  shopSpecial: () => api.get<ShopSpecialDto | null>('/api/v1/shop/special'),
  shopBuy: (goodsId: number, num: number) => api.post<Anything>('/api/v1/shop/buy', { goodsId, num }),
  shopBuySpecial: (num: number) => api.post<Anything>('/api/v1/shop/buy-special', { num }),
  shopBuyBlack: (goodsId: number, num: number) =>
    api.post<Anything>('/api/v1/shop/buy-black', { goodsId, num }),
  sell: (goodsId: number, num: number) => api.post<Anything>('/api/v1/shop/sell', { goodsId, num }),
  discard: (goodsId: number) => api.post<Anything>('/api/v1/shop/discard', { goodsId }),

  store: (type?: number) => api.get<StoreDto>(`/api/v1/store/list${qs({ type })}`),
  storeRecords: (range: string) => api.get<LedgerRecordDto[]>(`/api/v1/store/records${qs({ range })}`),
  useGoods: (goodsId: number, num: number) => api.post<Anything>('/api/v1/store/use', { goodsId, num }),

  tasks: () => api.get<QuestsDto>('/api/v1/task/list'),
  activation: () => api.get<ActivationDto>('/api/v1/task/activation'),
  claimTask: (taskId: number) => api.post<Anything>('/api/v1/task/claim', { taskId }),
  /** 章末奖励（问题记录 318） */
  claimChapter: (chapterId: number) => api.post<Anything>('/api/v1/task/chapter', { chapterId }),
  claimActivation: (points: number) => api.post<Anything>('/api/v1/task/activation/claim', { points }),
  signIn: () => api.post<Anything>('/api/v1/task/signin'),
  friendList: (sort: 'level' | 'star' | 'recent' = 'level') =>
    api.get<FriendsDto>(`/api/v1/friend/list${qs({ sort })}`),
  friendRequests: () => api.get<FriendRequestDto[]>('/api/v1/friend/requests'),
  friendSearch: (q: string) => api.get<RestBriefDto[]>(`/api/v1/friend/search${qs({ q })}`),
  friendStreet: () => api.get<RestBriefDto[]>('/api/v1/friend/street'),
  friendApply: (restId: number) =>
    api.post<{ status: 'requested' | 'friends' }>('/api/v1/friend/apply', { restId }),
  friendRespond: (restId: number, accept: boolean) =>
    api.post<{ status: 'friends' | 'rejected' }>('/api/v1/friend/respond', { restId, accept }),
  friendRemove: (restId: number) => api.post<{ removed: true }>('/api/v1/friend/remove', { restId }),
  friendDetail: (restId: number) => api.get<FriendRestDto>(`/api/v1/friend/detail/${restId}`),
  friendFeed: (before?: string) => api.get<LogPageDto>(`/api/v1/friend/feed${qs({ before })}`),
  dineCurrent: () => api.get<DineCurrentDto | null>('/api/v1/dine/current'),
  dineStart: (restId: number, tableNo: number) =>
    api.post<Anything>('/api/v1/dine/start', { restId, tableNo }),
  dineEnd: () => api.post<DineRewardDto>('/api/v1/dine/end'),
  dineExpel: (tableNo: number) =>
    api.post<{ hostCoin: number; dinerLoss: number }>('/api/v1/dine/expel', { tableNo }),
  roachLay: (restId: number, tableNo: number) =>
    api.post<{ coin: number; exp: number }>('/api/v1/roach/lay', { restId, tableNo }),
  roachKill: (restId: number, tableNo: number) =>
    api.post<KillResultDto>('/api/v1/roach/kill', { restId, tableNo }),
  friendRefuel: (restId: number, num: number) =>
    api.post<{ oil: number; tickets: number }>('/api/v1/friend/refuel', { restId, num }),
  flipSlots: (restId: number) => api.get<FlipSlotsDto>(`/api/v1/friend/cupboard/${restId}`),
  flip: (restId: number, slotNo: number) =>
    api.post<FlipResultDto>('/api/v1/cupboard/flip', { restId, slotNo }),
  exchangeFoods: (restId: number, level: number) =>
    api.get<ExchangeFoodsDto>(`/api/v1/friend/foods/${restId}${qs({ level })}`),
  exchange: (b: { restId: number; giveFoodsId: number; takeFoodsId: number }) =>
    api.post<ExchangeResultDto>('/api/v1/foods/exchange', b),
  thumbsToday: () => api.get<ThumbTodayDto[]>('/api/v1/thumbs/today'),
  thumbUp: (restId: number) => api.post<ThumbResultDto>('/api/v1/thumbs/up', { restId }),
  thumbsReturnAll: () => api.post<ReturnAllDto>('/api/v1/thumbs/returnAll'),
  myLooks: () => api.get<MyLooksDto>('/api/v1/rest/looks'),
  setDoor: (door: number) => api.post<{ door: number }>('/api/v1/rest/door', { door }),
  setAvatar: (avatar: number) => api.post<{ avatar: number }>('/api/v1/rest/avatar', { avatar }),
  setNotice: (text: string) => api.post<{ notice: string }>('/api/v1/rest/notice', { text }),
  iconBuy: (key: string) => api.post<{ key: string }>('/api/v1/rest/icon/buy', { key }),
  iconShow: (iconId: number, shown: boolean) =>
    api.post<{ iconId: number; shown: boolean }>('/api/v1/rest/icon/show', { iconId, shown }),
  equipOverview: () => api.get<EquipOverviewDto>('/api/v1/equip/overview'),
  equipList: (part?: number) => api.get<EquipDto[]>(`/api/v1/equip/list${qs({ part })}`),
  equipDetail: (id: number) => api.get<EquipDetailDto>(`/api/v1/equip/item/${id}`),
  equipWear: (id: number) => api.post<Anything>('/api/v1/equip/wear', { id }),
  equipUnwear: (id: number) => api.post<Anything>('/api/v1/equip/unwear', { id }),
  equipUnwearAll: () => api.post<Anything>('/api/v1/equip/unwearAll'),
  equipStress: (id: number, stone: boolean) =>
    api.post<StressResultDto>('/api/v1/equip/stress', { id, stone }),
  equipRollback: (id: number, goodsId: number) =>
    api.post<{ stress: number }>('/api/v1/equip/rollback', { id, goodsId }),
  equipLock: (id: number, locked: boolean) => api.post<Anything>('/api/v1/equip/lock', { id, locked }),
  equipSalvage: (id: number) => api.post<{ essence: number }>('/api/v1/equip/salvage', { id }),
  equipSell: (id: number) => api.post<{ coin: number }>('/api/v1/equip/sell', { id }),
  equipBatch: (ids: number[], way: 'salvage' | 'sell') =>
    api.post<EquipBatchDto>('/api/v1/equip/batch', { ids, way }),
  equipDrill: (id: number) => api.post<{ curHole: number }>('/api/v1/equip/drill', { id }),
  equipInlay: (id: number, gemId: number) => api.post<Anything>('/api/v1/equip/inlay', { id, gemId }),
  equipUngem: (gemRowId: number) => api.post<{ coin: number }>('/api/v1/equip/ungem', { gemRowId }),
  gems: () => api.get<GemsDto>('/api/v1/gem/list'),
  gemLevelUp: (goodsId: number, num: number) =>
    api.post<GemLevelUpDto>('/api/v1/gem/levelup', { goodsId, num }),
  equipPresetSave: (name: string) => api.post<{ id: number }>('/api/v1/equip/preset/save', { name }),
  equipPresetApply: (id: number) => api.post<{ skipped: number[] }>('/api/v1/equip/preset/apply', { id }),
  equipPresetDelete: (id: number) => api.post<Anything>('/api/v1/equip/preset/delete', { id }),
  mc: () => api.get<McOverviewDto>('/api/v1/mc'),
  mcPreview: (mcId: number) => api.get<McPreviewDto>(`/api/v1/mc/${mcId}/preview`),
  mcAppraise: (toolId: number, times: number, noRetry: boolean) =>
    api.post<AppraiseResultDto>('/api/v1/mc/appraise', { toolId, times, noRetry }),
  mcRemnantSell: (mcId: number, num: number) =>
    api.post<{ coin: number }>('/api/v1/mc/remnant/sell', { mcId, num }),
  mcRemnantDecompose: (mcId: number, num: number) =>
    api.post<{ goodsId: number; num: number }>('/api/v1/mc/remnant/decompose', { mcId, num }),
  /** 碎片兑换指定残卷（问题记录 415） */
  mcExchange: (mcId: number, num: number) =>
    api.post<{ mcId: number; num: number }>('/api/v1/mc/remnant/exchange', { mcId, num }),
  mcLearn: (mcId: number) => api.post<{ mcId: number }>('/api/v1/mc/learn', { mcId }),
  mcLearnAll: () => api.post<{ learned: number[] }>('/api/v1/mc/learnAll'),
  mcCook: (mcId: number, cookNum: number, cookie: boolean) =>
    api.post<CookResultDto>('/api/v1/mc/cook', { mcId, cookNum, cookie }),
  mcDump: () => api.post<{ id: number }>('/api/v1/mc/dump'),
  mcTaste: (restId: number) => api.post<TasteResultDto>('/api/v1/mc/taste', { restId }),
  lessons: () => api.get<LessonsDto>('/api/v1/mc/lessons'),
  lessonOpen: (mcId: number, certId: number) =>
    api.post<{ id: number }>('/api/v1/mc/lesson/open', { mcId, certId }),
  lessonLearn: (id: number, type: 1 | 2) =>
    api.post<LessonLearnDto>(`/api/v1/mc/lesson/${id}/learn`, { type }),
  lessonClose: () => api.post<{ id: number }>('/api/v1/mc/lesson/close'),
  temple: () => api.get<TempleDto>('/api/v1/temple'),
  templeMissile: (goodsId: number, num: number) =>
    api.post<MissileResultDto>('/api/v1/temple/missile', { goodsId, num }),
  templeExplore: (goodsId: number, times: number) =>
    api.post<ExploreResultDto>('/api/v1/temple/explore', { goodsId, times }),
  trialPrepare: (way: 1 | 2) => api.post<{ mcId: number }>('/api/v1/temple/trial/prepare', { way }),
  trialRefresh: (mcId?: number) =>
    api.post<{ mcId: number }>('/api/v1/temple/trial/refresh', mcId === undefined ? {} : { mcId }),
  trialStart: (mainFoodsId: number, subFoodsId: number) =>
    api.post<TrialResultDto>('/api/v1/temple/trial/start', { mainFoodsId, subFoodsId }),
  krakenFeed: (num: number) => api.post<KrakenFeedDto>('/api/v1/temple/kraken/feed', { num }),
  tentacleShop: () => api.get<TentacleShopDto>('/api/v1/temple/tentacle'),
  tentacleRefresh: () => api.post<TentacleShopDto>('/api/v1/temple/tentacle/refresh'),
  tentacleExchange: (slot: number) => api.post<TentacleShopDto>('/api/v1/temple/tentacle/exchange', { slot }),
  yard: () => api.get<YardDto>('/api/v1/yard'),
  yardFriend: (restId: number) => api.get<FriendYardDto>(`/api/v1/yard/friend/${restId}`),
  yardExpand: () => api.post<{ no: number; coin: number }>('/api/v1/yard/land/expand'),
  yardPlant: (landNo: number, seedId: number) =>
    api.post<{ plantId: number }>('/api/v1/yard/plant', { landNo, seedId }),
  yardWater: (plantId: number) => api.post<{ stage: number }>('/api/v1/yard/water', { plantId }),
  yardFeed: (plantId: number, goodsId: number) =>
    api.post<{ feedMin: number }>('/api/v1/yard/feed', { plantId, goodsId }),
  yardWeed: (plantId: number) => api.post<{ plantId: number }>('/api/v1/yard/weed', { plantId }),
  yardDeworm: (plantId: number) => api.post<{ plantId: number }>('/api/v1/yard/deworm', { plantId }),
  yardRemove: (plantId: number) => api.post<{ seedBack: boolean }>('/api/v1/yard/remove', { plantId }),
  yardReap: (plantId: number) => api.post<ReapResultDto>('/api/v1/yard/reap', { plantId }),
  basket: () => api.get<BasketDto>('/api/v1/yard/basket'),
  basketStore: (foodsId: number, num: number) =>
    api.post<{ stored: number; dropped: number }>('/api/v1/yard/basket/store', { foodsId, num }),
  formulas: () => api.get<FormulasDto>('/api/v1/yard/formulas'),
  formulaAppraise: (toolId: number, times: number) =>
    api.post<FormulaAppraiseResultDto>('/api/v1/yard/formula/appraise', { toolId, times }),
  formulaLearn: (formulaId: number) =>
    api.post<{ formulaId: number }>('/api/v1/yard/formula/learn', { formulaId }),
  formulaDecompose: (formulaId: number, part: 'main' | 'sub', num: number) =>
    api.post<{ essence: number }>('/api/v1/yard/formula/decompose', { formulaId, part, num }),
  formulaCompose: (formulaId: number, num: number) =>
    api.post<ComposeResultDto>('/api/v1/yard/formula/compose', { formulaId, num }),
  seeds: () => api.get<SeedsDto>('/api/v1/yard/seeds'),
  seedBuy: (seedId: number, num: number) =>
    api.post<{ coin: number }>('/api/v1/yard/seed/buy', { seedId, num }),
  seedExchange: (seedId: number, times: number) =>
    api.post<{ seeds: number }>('/api/v1/yard/seed/exchange', { seedId, times }),
  bar: () => api.get<BarDto>('/api/v1/bar'),
  barFg: (hand: number) => api.post<FgResultDto>('/api/v1/bar/fg', { hand }),
  /** round：面板上看到的这一轮（没有局为 null），和服务端对不上时报 cup_round */
  barCupGuess: (cup: number, round: number | null) =>
    api.post<CupDto>('/api/v1/bar/cup/guess', { cup, round }),
  barCupStop: () => api.post<CupDto>('/api/v1/bar/cup/stop'),
  barCupNext: () => api.post<CupDto>('/api/v1/bar/cup/next'),
  barNum: (num: number) => api.post<NumResultDto>('/api/v1/bar/num', { num }),
  barSlot: (times: number) => api.post<SlotResultDto>('/api/v1/bar/slot', { times }),
  barExchange: (num: number) => api.post<BarExchangeResultDto>('/api/v1/bar/exchange', { num }),
  barDevilStart: (stake: number) => api.post<DevilDto>('/api/v1/bar/devil/start', { stake }),
  barDevilDrink: (cup: number) => api.post<DevilDto>('/api/v1/bar/devil/drink', { cup }),
  barMemoryStart: () => api.post<MemoryRoundDto>('/api/v1/bar/memory/start'),
  barMemoryAnswer: (answer: number[]) => api.post<MemoryAnswerDto>('/api/v1/bar/memory/answer', { answer }),
  barMemoryNext: () => api.post<MemoryRoundDto>('/api/v1/bar/memory/next'),
  barMemoryStop: () => api.post<Record<string, never>>('/api/v1/bar/memory/stop'),
  barDartsStart: () => api.post<DartsDto>('/api/v1/bar/darts/start'),
  barDartsAim: () => api.post<DartsAimDto>('/api/v1/bar/darts/aim'),
  barDartsThrow: (elapsedMs: number) => api.post<DartsThrowDto>('/api/v1/bar/darts/throw', { elapsedMs }),
  barNimStart: (table: 'novice' | 'expert') => api.post<NimDto>('/api/v1/bar/nim/start', { table }),
  barNimFirst: (who: 'me' | 'bartender') => api.post<NimDto>('/api/v1/bar/nim/first', { who }),
  barNimTake: (num: number) => api.post<NimDto>('/api/v1/bar/nim/take', { num }),
  barDealStart: () => api.post<DealDto>('/api/v1/bar/deal/start'),
  barDealPick: (box: number) => api.post<DealDto>('/api/v1/bar/deal/pick', { box }),
  barDealOpen: (box: number) => api.post<DealDto>('/api/v1/bar/deal/open', { box }),
  barDealAnswer: (deal: boolean) => api.post<DealDto>('/api/v1/bar/deal/answer', { deal }),
  barSpiceStart: () => api.post<SpiceDto>('/api/v1/bar/spice/start'),
  barSpiceGuess: (guess: number[]) => api.post<SpiceDto>('/api/v1/bar/spice/guess', { guess }),
  tower: () => api.get<TowerDto>('/api/v1/tower'),
  towerChallenge: (floor: number, test: boolean) =>
    api.post<DuelResultDto>('/api/v1/tower/challenge', { floor, test }),
  towerRank: () => api.get<RankDto>('/api/v1/tower/rank'),
  rankOccupy: (rank: number) => api.post<{ rank: number }>('/api/v1/tower/rank/occupy', { rank }),
  rankChallenge: (rank: number) => api.post<DuelResultDto>('/api/v1/tower/rank/challenge', { rank }),
  duelInfo: (restId: number) => api.get<DuelInfoDto>(`/api/v1/tower/duel/${restId}`),
  friendDuel: (restId: number) => api.post<DuelResultDto>('/api/v1/tower/duel', { restId }),
  renownShop: () => api.get<RenownShopDto>('/api/v1/tower/shop'),
  renownBuy: (goodsId: number, num: number) =>
    api.post<{ renown: number }>('/api/v1/tower/shop/buy', { goodsId, num }),
  takeaway: () => api.get<TakeawayDto>('/api/v1/takeaway'),
  takeawayOpen: (way: 'ticket' | 'coin') => api.post<{ opened: true }>('/api/v1/takeaway/open', { way }),
  takeawayRefresh: () => api.post<{ created: number }>('/api/v1/takeaway/refresh'),
  takeawayDeliver: (orderId: number, riderId: number, double: boolean) =>
    api.post<TakeawayDeliveryDto>('/api/v1/takeaway/deliver', { orderId, riderId, double }),
  takeawayClaim: (deliveryId: number, drone: boolean) =>
    api.post<TakeawayClaimDto>('/api/v1/takeaway/claim', { deliveryId, drone }),
  takeawayClaimAll: () => api.post<TakeawayClaimDto[]>('/api/v1/takeaway/claim-all'),
  takeawayCandidates: () => api.get<RiderCandidateDto[]>('/api/v1/takeaway/candidates'),
  takeawayHire: (restId: number) => api.post<{ riderId: number }>('/api/v1/takeaway/hire', { restId }),
  takeawayDismiss: (riderId: number) =>
    api.post<{ coin: number; exp: number }>('/api/v1/takeaway/dismiss', { riderId }),
  town: () => api.get<TownDto>('/api/v1/town'),
  townNews: (before?: number) =>
    api.get<NewsPageDto>(before === undefined ? '/api/v1/town/news' : `/api/v1/town/news?before=${before}`),
  /** 小镇日报（2026-10-08）：不带日期取最近一份已发布的 */
  townDaily: (day?: string) =>
    api.get<DailyDto>(day === undefined ? '/api/v1/town/daily' : `/api/v1/town/daily?day=${day}`),
  townExchange: (part: TownExchangePart) => api.get<TownExchangeDto>(`/api/v1/town/exchange?part=${part}`),
  townBroadcast: (text: string) => api.post<{ text: string }>('/api/v1/town/broadcast', { text }),
  townTalk: (npc: NpcKey) => api.post<TalkResultDto>('/api/v1/town/talk', { npc }),
  townShake: () => api.post<ShakeResultDto>('/api/v1/town/shake'),
  townMayor: (place: number) => api.post<TalkResultDto>('/api/v1/town/mayor', { place }),
  rank: (key: string) => api.get<LeaderboardDto>(`/api/v1/rank/${encodeURIComponent(key)}`),
  forumList: (q: { tab: ForumTab; q?: string; cursor?: string }) =>
    api.get<ForumListDto>(`/api/v1/forum/posts${qs(q)}`),
  forumPost: (id: number) => api.get<ForumPostDetailDto>(`/api/v1/forum/posts/${id}`),
  forumSource: (id: number) => api.get<ForumPostSourceDto>(`/api/v1/forum/posts/${id}/source`),
  forumCreate: (b: ForumPostBody) => api.post<{ id: number }>('/api/v1/forum/posts', b),
  forumEdit: (id: number, b: ForumPostBody) => api.post<{ id: number }>(`/api/v1/forum/posts/${id}/edit`, b),
  forumDelete: (id: number) => api.post<Anything>(`/api/v1/forum/posts/${id}/delete`),
  forumReply: (id: number, b: Partial<ForumReplyBody> & { content: string }) =>
    api.post<ForumReplyDto>(`/api/v1/forum/posts/${id}/replies`, b),
  forumDeleteReply: (id: number) => api.post<Anything>(`/api/v1/forum/replies/${id}/delete`),
  forumReact: (id: number, kind: 'up' | 'down') =>
    api.post<ForumReactDto>(`/api/v1/forum/posts/${id}/react`, { kind }),
  forumReads: (id: number) => api.get<ForumReadsDto>(`/api/v1/forum/posts/${id}/reads`),
  forumAdmin: (id: number, action: ForumAdminAction) =>
    api.post<ForumAdminDto>(`/api/v1/forum/posts/${id}/admin`, { action }),
  hiphopSpot: (q: { place: number } | { restId: number }) => api.get<HiphopSpotDto>(`/api/v1/hiphop${qs(q)}`),
  hiphopTip: (b: HiphopTipBody) => api.post<HiphopTipDto>('/api/v1/hiphop/tip', b),
  townHammer: (body: { mode: 'coin'; type: number } | { mode: 'diamond' }) =>
    api.post<HammerResultDto>('/api/v1/town/hammer', body),
  townExchangeDo: (id: number, num: number) =>
    api.post<TownExchangeResultDto>('/api/v1/town/exchange', { id, num }),
  townLevelTicket: (level: number, picks: Array<{ foodsId: number; num: number }>) =>
    api.post<TicketResultDto>('/api/v1/town/level-ticket', { level, picks }),
  townMysteryTicket: (foodsId: number) =>
    api.post<TicketResultDto>('/api/v1/town/mystery-ticket', { foodsId }),
  townWish: () => api.post<WishResultDto>('/api/v1/town/wish'),
  townFeast: (foodsId?: number) =>
    api.post<FeastResultDto>('/api/v1/town/feast', foodsId === undefined ? {} : { foodsId }),
  announcements: () => api.get<AnnouncementsDto>('/api/v1/announcements'),
  announcementSeen: (id: number) => api.post<null>(`/api/v1/announcements/${id}/seen`, {}),
  publicAnnouncements: () => api.get<AnnouncementsDto>('/api/v1/public/announcements'),
  // 友情链接、服务器时间（问题记录 348）
  links: () => api.get<LinkDto[]>('/api/v1/links'),
  serverTime: () => api.get<ServerTimeDto>('/api/v1/time'),
  mail: () => api.get<MailListDto>('/api/v1/mail'),
  redeem: (code: string) => api.post<RedeemResultDto>('/api/v1/redeem', { code }),
  guideCodes: () => api.get<GuideCodeDto[]>('/api/v1/guide/codes'),
  invite: () => api.get<InviteDto>('/api/v1/invite'),
  report: (b: ReportInput) => api.post<{ ok: true }>('/api/v1/report', b),
  mailUnread: () => api.get<{ count: number }>('/api/v1/mail/unread'),
  mailRead: (id: number) => api.post<void>(`/api/v1/mail/${id}/read`, {}),
  mailClaim: (id: number) => api.post<MailClaimDto>(`/api/v1/mail/${id}/claim`, {}),
  mailClaimAll: () => api.post<MailClaimAllDto>('/api/v1/mail/claim-all', {}),
  activities: () => api.get<ActivitiesDto>('/api/v1/activities'),
  activitySummary: () => api.get<ActivitySummaryDto>('/api/v1/activities/summary'),
  activityClaim: (id: number, key: string) =>
    api.post<ActivityClaimDto>(`/api/v1/activities/${id}/claim`, { key }),
  activityClaimAll: (id: number) => api.post<ActivityClaimDto>(`/api/v1/activities/${id}/claim-all`, {}),
  tradeFoods: () => api.get<ExchangeFoodDto[]>('/api/v1/exchange/foods'),
  tradeBook: (foodsId: number) => api.get<ExchangeBookDto>(`/api/v1/exchange/book/${foodsId}`),
  tradeMe: () => api.get<ExchangeMeDto>('/api/v1/exchange/me'),
  tradePlace: (b: { foodsId: number; side: 'buy' | 'sell'; price: number; qty: number }) =>
    api.post<ExchangePlaceDto>('/api/v1/exchange/orders', b),
  /** 卖给系统（问题记录 244）：price 是看到的系统收购价 */
  tradeSellSystem: (b: { foodsId: number; price: number; qty: number }) =>
    api.post<ExchangePlaceDto>('/api/v1/exchange/sell-system', b),
  /** 食材期货（期货设计 §9） */
  futures: () => api.get<FuturesDto>('/api/v1/futures'),
  futuresOrder: (b: FuturesOrderInput) => api.post<FuturesContractDto>('/api/v1/futures/order', b),
  futuresCancel: (id: number) => api.post<FuturesContractDto>(`/api/v1/futures/${id}/cancel`, {}),
  tradeCancel: (id: number) => api.post<ExchangeOrderDto>(`/api/v1/exchange/orders/${id}/cancel`, {}),
  tradeWithdraw: () => api.post<ExchangeWithdrawDto>('/api/v1/exchange/withdraw', {}),
  /** line 不传是普通池；豪华一番赏传 'deluxe'（240-2） */
  kuji: (line?: KujiLine) => api.get<KujiViewDto>(`/api/v1/kuji${line === 'deluxe' ? '?line=deluxe' : ''}`),
  kujiBuy: (num: number, line?: KujiLine) =>
    api.post<KujiViewDto>('/api/v1/kuji/buy', { num, ...(line ? { line } : {}) }),
  kujiDraw: (num: number, line?: KujiLine) =>
    api.post<KujiDrawDto>('/api/v1/kuji/draw', { num, ...(line ? { line } : {}) }),
  // 小镇发展基金（240-2）
  // 收购（问题记录 421）
  acquire: () => api.get<AcquireViewDto>('/api/v1/acquire'),
  acquireRest: (restId: number) => api.get<AcquireRestDto>(`/api/v1/acquire/rest/${restId}`),
  acquireRank: (board: 'price' | 'invest') => api.get<AcquireRankDto>(`/api/v1/acquire/rank?board=${board}`),
  acquireMarket: () => api.get<AcquireMarketDto>('/api/v1/acquire/market'),
  acquireBuy: (restId: number, way: 'acquire' | 'listed', expect: number) =>
    api.post<AcquireResultDto>('/api/v1/acquire/buy', { restId, way, expect }),
  acquireRedeem: (expect: number) => api.post<AcquireResultDto>('/api/v1/acquire/redeem', { expect }),
  acquireRelease: (restId: number) => api.post<{ restId: number }>('/api/v1/acquire/release', { restId }),
  acquireList: (restId: number, rate: number) =>
    api.post<{ restId: number; rate: number; until: string }>('/api/v1/acquire/list', { restId, rate }),
  acquireUnlist: (restId: number) => api.post<{ restId: number }>('/api/v1/acquire/unlist', { restId }),
  acquireTend: () => api.post<AcquireTendDto>('/api/v1/acquire/tend', {}),
  fund: () => api.get<FundViewDto>('/api/v1/fund'),
  fundDeposit: (tier: string) => api.post<FundViewDto>('/api/v1/fund/deposit', { tier }),
  fundClaim: () => api.post<FundViewDto>('/api/v1/fund/claim', {}),
  fundWithdraw: () => api.post<FundViewDto>('/api/v1/fund/withdraw', {}),
  bulk: () => api.get<BulkDto>('/api/v1/bulk'),
  bulkBid: (body: BulkBidInput) => api.post<BulkDto>('/api/v1/bulk/bid', body),
  wealth: () => api.get<WealthViewDto>('/api/v1/wealth'),
  wealthDeposit: (days: number, coin: number) =>
    api.post<WealthViewDto>('/api/v1/wealth/deposit', { days, coin }),
  wealthClaim: (id: number) => api.post<WealthViewDto>(`/api/v1/wealth/${id}/claim`, {}),
  wealthWithdraw: (id: number) => api.post<WealthViewDto>(`/api/v1/wealth/${id}/withdraw`, {}),
  predictList: () => api.get<PredictListDto>('/api/v1/predict/events'),
  predictDetail: (id: number) => api.get<PredictDetailDto>(`/api/v1/predict/events/${id}`),
  predictTrade: (id: number, b: { side: 'yes' | 'no'; dir: 'buy' | 'sell'; qty: number; limit?: number }) =>
    api.post<PredictTradeDto>(`/api/v1/predict/events/${id}/trade`, b),
  activityUnlock: (id: number) => api.post<{ premium: true }>(`/api/v1/activities/${id}/unlock`, {}),
  activityExchange: (id: number, index: number, times: number) =>
    api.post<ActivityExchangeDto>(`/api/v1/activities/${id}/exchange`, { index, times }),
  mailDelete: (id: number) => api.post<void>(`/api/v1/mail/${id}/delete`, {}),
};
